name: imei_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # icons
  cupertino_icons: ^1.0.5
  # di
  get_it: ^7.6.0
  # bloc state manager
  flutter_bloc: ^8.1.3
  # forms
  formz: ^0.6.0
  # hive
  hive: ^2.2.3
  # equatable
  equatable: ^2.0.5
  # rest api
  dio: ^5.2.1+1
  dio_retry_plus: ^1.0.3
  # intl
  intl: ^0.18.0
  # chuck
  chuck_interceptor: ^2.0.0+1
  # sqFlite
  sqflite: ^2.2.8+4
  # internet checker
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  # url launcher
  url_launcher: ^6.1.11
  #http: parser
  http_parser: ^4.0.2
  #shimmer
  shimmer: ^3.0.0
  #flutter_scalable_ocr: ^2.0.0
  flutter_scalable_ocr: ^2.0.0
  # path
  path_provider: ^2.0.15
  # cached image
  cached_network_image: ^3.2.3
  # svg picture
  flutter_svg: ^2.0.7
  # firebase
  firebase_core: ^2.13.1
  firebase_remote_config: ^4.2.4
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.2
  firebase_crashlytics: ^3.3.2
  firebase_performance: ^0.9.2+2
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  #sign in with apple id
  sign_in_with_apple: ^4.3.0
  # local notifications
  flutter_local_notifications: ^14.1.1
  # box
  gap: ^3.0.0
  # native splash
  flutter_native_splash: ^2.3.1
  # pinput:
  pinput: ^2.2.31
  # share plus
  share_plus: ^7.0.2
  # location view
  maps_launcher: ^2.2.0
  # syncfusion_flutter_datepicker
  syncfusion_flutter_datepicker: ^21.2.10
  # image picker
  image_picker: ^0.8.8
  # slidable
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_flutter: ^1.1.0
  build_runner: ^2.4.5
  bloc_test: ^9.1.3
  mockito: ^5.4.2

flutter_native_splash:
  path: ..

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
